name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repo cloning
        uses: actions/checkout@v4

      - name: Server connecting
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 185.231.244.160
          username: root
          key: ${{ secrets.SERVER_SSH }}
          script: |
            cd /home/projects/appic/
            git pull
            ./build.sh
